### ISSUE TITLE
Enabled GFA breaks dialog system in G1

### ISSUE THREAD

**Issue by nicodex** [szapp/GothicFreeAim#176] opened 2017-10-03 20:34 UTC
During dialogs in the Old Camp, sooner or later, the cancel key and/or right mouse button is closing the subtitle window, but no longer stops the speech (the dialog system still waits for the end of the sound), sometimes the output text is shown in a noise window (red caption, as if talking to himself), and sometimes the dialog just ends.

This issue goes away as soon as GFA is disabled in the game menu (same game session, neither restart nor reload required).

All the smalltalk in the Old Camp might be an issue here, because it does not happen at the starting area.

edit: Also testing again with Beta 16, 17, and 18 - seems to be an older problem. No suspicious output in the zSpy. Will retest it with the German release (should be no difference, just to be sure).

**Comment by szapp** [comment] 2017-10-04 09:58
I can reproduce the bug with Gothic 1 (German version), but have never encountered it in Gothic 2. It seems to be connected to the free aiming feature only (`GFA_Init(GFA_RANGED)` and/or `GFA_Init(GFA_SPELLS)`, but none of the other [sub-features](https://github.com/szapp/GothicFreeAim/wiki/Features-and-Configuration#initialization-by-features)).

Additionally I found that cancelling OUs once sometimes cancels all consecutive lines of dialog.

So far, I  am clueless. The zSpy on maximum level does not give much info. GFA hooks the `oCGame::HandleEvent` to manipulate the cancellation of OUs, but only for Gothic 2. In Gothic 1 this hook is not present. I will start investigating in `CGameManager::HandleCancelKey`.

**Comment by szapp** [comment] 2017-10-04 12:19
I found the problem:
For some frequent checks on active aim movement, the player instance is retrieved with
```D
var oCNpc her; her = Hlp_GetNpc(hero);
```
This external function seems to overwrite the active talking NPC. Would you be willing to try if the problem is fixed for you if you replace this assignment in [line 34 in GFA_AimMovement](https://github.com/szapp/GothicFreeAim/blob/bad2c6b343362dfc0107bb3d6a9503d853f09ec4/_work/data/Scripts/Content/GFA/_intern/strafing.d#L34) like so:
```D
const int oCNpc__player = 9288624; //0x8DBBB0 // Gothic 1
var oCNpc her; her = _^(MEM_ReadInt(oCNpc__player));
```
For me this fixes the issue. Let me know it works for you as well.

**Comment by nicodex** [comment] 2017-10-04 12:39
Hlp_GetNpc() isn't doing anything tricky, __but__ it overrides the global variable 'ÿINSTANCE_HELP' (symbol index 0) that is internally used by every External that returns an instance object. This might conflict with other script code that is currently running.

Currently I'm using the VDF release of the beta and I'm not prepared to re-compile the scripts (will take a while to test the changes).

**Comment by szapp** [comment] 2017-10-04 12:41
Thanks for the info.

Since this small change does not hurt, I will implement it in the next beta release. Then you can test it without the need to compile the scripts yourself.

**Comment by szapp** [comment] 2017-10-10 19:34
Was this issue resolved with the new version (beta 20)?

**Closed** 2017-10-23 15:16 UTC
Labels: beta-test, bug, critical
